### ISSUE TITLE
Running without arguments causes exception

### ISSUE THREAD

**Issue by dmuth** [SierraSoftworks/blmain#13]
Hi!  First, thanks for making this tool.  I used it to convert like 90 of my repos in about 2 minutes, which saved me a couple of hours of manual labor!  The Dockerization is super handy as well!

That said, I got tripped up when I first ran the app.  I ran it without any arguments, hoping to get a syntax diagram so I could see if there were options in addition to what was specified in the README, and got a traceback instead:

```
$ docker run --rm -it sierrasoftworks/blmain 
Unhandled exception. System.AggregateException: One or more errors occurred. (String cannot be empty (Parameter 'token'))
 ---> System.ArgumentException: String cannot be empty (Parameter 'token')
```

I'm not much of a .NET person, but if there's a way to print out a syntax diagram when there are no arguments/bad arguments, that might be helpful to first time users.

Thanks!

-- Doug

**Comment by notheotherben** [comment]
Hi Doug, sorry for the terribly slow response here - afraid I got swamped with dependabot notifications and only just noticed this one.

Let me see what I can do to improve the situation there - in non .NET person terms - I'm probably not using the right tool for the job when it comes to a command line library. To be more specific, I'm using a configuration binding layer which can accept config properties from the command line args, rather than a dedicated command line library. There are definitely better options but, hey, this seemed like it might be worth a try.

Will let you know once that's replaced and I'm very happy to hear that it worked well for you  👍 (in my case it did about 200 repos worth and I haven't hit any issues so far - so I'm happy)
